AWSTemplateFormatVersion: '2010-09-09'
Description: Nested VPC stack 

Parameters:
  EnvironmentName:
    Type: String

  VpcCidr:
    Type: String

  PublicSubnet1Cidr:
    Type: String

  PublicSubnet2Cidr:
    Type: String

  PrivateSubnet1Cidr:
    Type: String

  PrivateSubnet2Cidr:
    Type: String

Mappings:
  RegionMap:
    eu-west-2:
      AZ1: eu-west-2a
      AZ2: eu-west-2b

Resources:

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PublicSubnet1Cidr
      AvailabilityZone: !FindInMap [RegionMap, !Ref 'AWS::Region', AZ1]
      MapPublicIpOnLaunch: true

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PublicSubnet2Cidr
      AvailabilityZone: !FindInMap [RegionMap, !Ref 'AWS::Region', AZ2]
      MapPublicIpOnLaunch: true

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PrivateSubnet1Cidr
      AvailabilityZone: !FindInMap [RegionMap, !Ref 'AWS::Region', AZ1]

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PrivateSubnet2Cidr
      AvailabilityZone: !FindInMap [RegionMap, !Ref 'AWS::Region', AZ2]

Outputs:

  VpcId:
    Value: !Ref VPC

  PublicSubnet1Id:
    Value: !Ref PublicSubnet1

  PublicSubnet2Id:
    Value: !Ref PublicSubnet2

  PrivateSubnet1Id:
    Value: !Ref PrivateSubnet1

  PrivateSubnet2Id:
    Value: !Ref PrivateSubnet2